Create python-package.yml
EducationalTestingService/match pull request #18
Opened 2022-07-25 12:28 UTC by tamarl08

2022-07-25 13:09 UTC, slava92 submitted a review, later dismissed
Looks great!

2022-07-25 13:21 UTC, desilinguist requested changes

2022-07-25 13:21 UTC, desilinguist commented on .github/workflows/python-package.yml
> +name: Python package
We should rename this right since this action is not about packaging?

2022-07-25 13:23 UTC, desilinguist commented
This looks great, @tamarl08 ! I just had a minor comment. Also, I think we need to resolve at least the branch naming discussion on the discussions [page](https://github.com/EducationalTestingService/match/discussions) before we merge this PR.

2022-07-28 14:21 UTC, desilinguist approved these changes, later dismissed
LGTM!

2022-07-28 14:21 UTC, desilinguist commented
Can we get rid of the `.travis.yml` file too please?

2022-07-28 17:26 UTC, desilinguist submitted a review, later dismissed
Looks great!

2022-08-01 15:59 UTC, desilinguist approved these changes

2022-08-01 16:00 UTC, merged